// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuY0fuKAEdYfWlFkjwRnf0ip5S2JI9U24',
    appId: '1:837241818672:web:f2ed2774dad5ade6ece7f5',
    messagingSenderId: '837241818672',
    projectId: 'chit-chat-90732',
    authDomain: 'chit-chat-90732.firebaseapp.com',
    storageBucket: 'chit-chat-90732.appspot.com',
    measurementId: 'G-2XY56YZWC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh668iuwYCnvsPV-bgukqeM-XOnG1PKGk',
    appId: '1:837241818672:android:bda9b3c7798af1e9ece7f5',
    messagingSenderId: '837241818672',
    projectId: 'chit-chat-90732',
    storageBucket: 'chit-chat-90732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJfPpIP2_A4ZqsbQMnALOcROTEWiHPIk',
    appId: '1:837241818672:ios:ab9331cf5454046dece7f5',
    messagingSenderId: '837241818672',
    projectId: 'chit-chat-90732',
    storageBucket: 'chit-chat-90732.appspot.com',
    iosBundleId: 'com.example.chitChat',
  );
}
