// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK4PrxcTd1JRYNXonBpU3TQNnq9nmvnXQ',
    appId: '1:742098681258:web:48616593e1a42c32b8bfd3',
    messagingSenderId: '742098681258',
    projectId: 'chitchatting-75f2b',
    authDomain: 'chitchatting-75f2b.firebaseapp.com',
    storageBucket: 'chitchatting-75f2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagXGlatzkOqFjpuNhqm-lNQWUu6kbORQ',
    appId: '1:742098681258:android:5262aba1d4d1cac6b8bfd3',
    messagingSenderId: '742098681258',
    projectId: 'chitchatting-75f2b',
    storageBucket: 'chitchatting-75f2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3FTzkOZ2CY43MBUsSVODHT8SFrVQomGI',
    appId: '1:742098681258:ios:754589ff1b91bff3b8bfd3',
    messagingSenderId: '742098681258',
    projectId: 'chitchatting-75f2b',
    storageBucket: 'chitchatting-75f2b.appspot.com',
    iosBundleId: 'com.example.chitChat',
  );

}